# Use Debian Trixie as it matches current Raspberry Pi OS
FROM debian:trixie

# Install build dependencies
RUN apt-get update && apt-get install -y \
    debhelper \
    devscripts \
    python3 \
    python3-flask \
    && rm -rf /var/lib/apt/lists/*

# Create a directory for the source and the output
WORKDIR /build/source

# Copy the source code
COPY . .

# Build the package and move it to the /output volume
CMD sh -c "dpkg-buildpackage -us -uc -b && cp ../vanlan-router_*.deb /output/"
